
import { Inter } from "next/font/google";
import "./globals.css";

import "bootstrap/dist/css/bootstrap.css";
// import "bootstrap/dist/js/bootstrap.bundle.min.js"; // Import Bootstrap JS
import Topbar from "@/components/Topbar";
import Bootstrap from "@/components/Bootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flipcart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
 // Add empty dependency array to useEffect to run only once
  
 return (
   <html lang="en">
      <body className={inter.className}>
      <Bootstrap />
        <Topbar />
        {children}
      </body>
    </html>
  );
}
