/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/P5u8gdBO53s
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function Registration() {
  return (
    (<div className="mx-auto max-w-sm space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Create an account</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your information to get started</p>
      </div>
      <div className="space-y-2">
        <Label htmlFor="name">Name</Label>
        <Input id="name" placeholder="Enter your name" required />
      </div>
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input id="email" placeholder="Enter your email" required />
      </div>
      <div className="space-y-2">
        <Label htmlFor="phone">Phone number</Label>
        <Input id="phone" placeholder="Enter your phone number" required />
      </div>
      <div className="space-y-2">
        <Label htmlFor="password">Password</Label>
        <Input id="password" placeholder="Enter your password" required type="password" />
      </div>
      <div className="space-y-2">
        <div className="flex items-center">
          <Checkbox id="agree" />
          <Label className="ml-2 leading-none" htmlFor="agree">
            I agree to the
            <Link className="underline" href="#">
              terms and conditions
            </Link>
          </Label>
        </div>
      </div>
      <Button className="w-full">Sign Up</Button>
    </div>)
  );
}
